//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPosition
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int DepartmentId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime PostedDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
    }
}
